### ISSUE TITLE
Review Vietnamese

### ISSUE THREAD

**Issue by alexeiva** [alexeiva/poiretone#1]
@crystaltype Could you please have a look at my Vietnamese characters?

There are PDFs in the [docs folder](https://github.com/alexeiva/poiretone/tree/master/docs)
<img width="1029" alt="screen shot 2016-07-12 at 19 16 42" src="https://cloud.githubusercontent.com/assets/16634089/16787101/a15ca97a-4867-11e6-9d72-b0328f6bf39b.png">

**Comment by alexeiva** [comment]
Here is the dong symbol:
<img width="390" alt="screen shot 2016-07-12 at 19 35 49" src="https://cloud.githubusercontent.com/assets/16634089/16787129/df19cc3e-4867-11e6-86c7-b2a6e70d8715.png">

**Comment by crystaltype** [comment]
Hi Alexei, I think they're good. But still they has some issues:
- the circumflex and grave combination: you shouldn't place the grave that low, they'll be hard to distinguish at small size. I think we should pull the grave up a little bit.
- the circumflex and hookabove combination: Acircumflexhookabove, Ocircumflexhookabove and Ecircumflexhookabove: again, the hookabove is placed too low compared to the circumflex. Is it your intention? If so, I don't quite understand the reason for that.
- The hookabove should have consistent size across the font. 
- the idotbelow is having problem with the dotbelow, it's out of line.
- The ydotbelow: we rather put the dotbelow to the right of y, just like y., not directly under it. 
- dotbelow on ocircumflexdotbelow, ohorndotbelow and odotbelow is placed too far from the base letter, compared to others.

That's all I picked up after looking at the screen. By the way, good job! :3

**Comment by alexeiva** [comment]
@crystaltype, Thank you very much for the detailed and structured feedback. I will look into this tomorrow. My design decisions were based on what fonts I could examine, mostly system fonts: lucida sans, etc. Could you recommended a good font for reference were the accents look good to you? Preferably open-source

**Comment by alexeiva** [comment]
@crystaltype, I have made the changes. Does this look right now?

> [x] the circumflex and grave combination: you shouldn't place the grave that low, they'll be hard to distinguish at small size. I think we should pull the grave up a little bit.

<img width="1038" alt="grave" src="https://cloud.githubusercontent.com/assets/16634089/16820328/74626e66-491e-11e6-98dd-c732e722526f.png">
<img width="1049" alt="acute" src="https://cloud.githubusercontent.com/assets/16634089/16820330/7464f640-491e-11e6-9fb5-89687501af23.png">

> [x] the circumflex and hookabove combination: Acircumflexhookabove, Ocircumflexhookabove and Ecircumflexhookabove: again, the hookabove is placed too low compared to the circumflex. Is it your intention? If so, I don't quite understand the reason for that.
> [x]The hookabove should have consistent size across the font. 
> <img width="1271" alt="hookabove" src="https://cloud.githubusercontent.com/assets/16634089/16820329/74631c3a-491e-11e6-8047-49f19cb0e6c9.png">
> 
> [x]the idotbelow is having problem with the dotbelow, it's out of line.
> [x]The ydotbelow: we rather put the dotbelow to the right of y, just like y., not directly under it. 
> [x]dotbelow on ocircumflexdotbelow, ohorndotbelow and odotbelow is placed too far from the base letter, compared to others.
> 
> <img width="848" alt="dot" src="https://cloud.githubusercontent.com/assets/16634089/16820441/00e34810-491f-11e6-9b7d-c21ad0e55233.png">
